# HTCondor submit file adaptado para CIEMAT con rutas absolutas

Executable = /nfs/cms/arqolmo/GPU_train/Bachelors-Thesis-Gregor-Brodbek/train_script/train_onnx_olmo.sh
Arguments  = $(ClusterId) $(ProcId)

Log    = /nfs/cms/arqolmo/GPU_train/Bachelors-Thesis-Gregor-Brodbek/condor_logs/$(ClusterId).$(ProcId).log
Output = /nfs/cms/arqolmo/GPU_train/Bachelors-Thesis-Gregor-Brodbek/condor_logs/$(ClusterId).$(ProcId).out
Error  = /nfs/cms/arqolmo/GPU_train/Bachelors-Thesis-Gregor-Brodbek/condor_logs/$(ClusterId).$(ProcId).err

initialdir = /nfs/cms/arqolmo/GPU_train/Bachelors-Thesis-Gregor-Brodbek

# NO transferimos archivos grandes
+RequiresGpu = True
+CieRunInGpu2 = True

# Exportar la API key si quieres hacerlo dinámico (setea antes de submit)
environment = "WANDB_API_KEY=f2470aaa16971ff802988e3c23714651ca4e4cbd"

Queue
